### ISSUE TITLE
Doesn't run with module `dot 1.1.1`

### ISSUE THREAD

**Issue by green-coder** [NetsBlox/NetsBlox#1025]
Hi, when we do a fresh install of NetsBlox, it crash when we do `npm start`. It can be fixed by updating a more recent version (1.1.2) of the `dot` module:

```
npm install dot@1.1.2 --save
```

**Comment by brollb** [comment]
Thanks for the feedback! I think this may be due to an outdated `npm-shrinkwrap.json` (I update it before each release) but should be an easy fix!

**Comment by brollb** [comment]
This should be fixed as of #1026 - let me know if you have any other issues!
