### ISSUE TITLE
problem with importing web libraries

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1029]
it's not possible to load "web services access" library. 

> expected single or double quoted attribute value

is this introduced in netsblox or snap related ? 
this is functional in current snap website

**Comment by brollb** [comment]
it also seems to be functional on `editor.netsblox.org` so I think it was introduced recently

**Comment by hamidzr** [comment]
It also happens on some other libraries.

**Comment by hamidzr** [comment]
Uncaught Error: Expected single- or double-quoted attribute value
gui.js: 731            blocks = this.serializer.loadBlocks(str, myself.stage);
store.js

**Comment by brollb** [comment]
Caused by https://github.com/brollb/snap-undo/issues/327
