### ISSUE TITLE
Request-Reply blocks

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1039]
We should consider adding "request-reply" blocks.

Should probably also add a "sender" reporter to be used in message hat block scripts

**Comment by hamidzr** [comment]
Can you expand on that? like the web block?

**Comment by brollb** [comment]
I imagine the request block would look like the http block. The response block should be a block that doesn't have a field for the target and should only be able to be used after the message received hat block. Does that make sense?

**Comment by hamidzr** [comment]
so what ever block that is put into response gets to run after the request is finished?

**Comment by brollb** [comment]
Basically, it should probably make a synchronous request to another
netsblox role so it should block until it gets a response from the other
role.

**Comment by brollb** [comment]
For example, if you wanted to make a file server in netsblox and request a list of the files to prompt the user about viewing a file, you might want to do something like the following on the client:

![request](https://user-images.githubusercontent.com/4982789/26946396-b6d6e152-4c54-11e7-83d3-d53ed0e7d7cd.png)

And reply as follows on the server:
![reply](https://user-images.githubusercontent.com/4982789/26946398-b8108546-4c54-11e7-990a-fd2ff7cd2813.png)

**Comment by brollb** [comment]
what about `send msg and wait` and adding a `sender` option to the send message block? The remaining question will be if we should have the `send msg and wait` block be a reporter or a command block...

**Comment by hamidzr** [comment]
`sender` or `receiver` option?
