### ISSUE TITLE
Increase default minimum earthquake size for earthquakes example

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1138]

**Comment by ellienguyen** [comment]
I think the default min should be kept at 3 because we don't have big earthquakes in Nashville and that default range ensures we get enough earthquakes

**Comment by brollb** [comment]
Fixed as of https://github.com/NetsBlox/NetsBlox/commit/29b6f436c03dcbe7ce96b2428f429741874b2f56
