### ISSUE TITLE
Incorrect number of movie titles in MovieDB

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1141]
Arnold Schwarzenegger returned only being cast in 4 movies when he should have been cast in many more...

We should check if this is an issue with TMDB or if it is something we can fix on our end

**Comment by ellienguyen** [comment]
It is because there are two methods: personCastMovieID and personCrewMovieID. The cast one will return many more films
![image](https://user-images.githubusercontent.com/18899970/27446197-5222a32e-5742-11e7-9573-dea4b1974084.png)

**Comment by ellienguyen** [comment]
I would change the interface for MovieDB: using APIConsumer, simplify interface and get rid of duplicated or confusing calls (like between cast and crew)

**Comment by brollb** [comment]
I think that is a good idea but we should probably do that in another issue bc it would be more involved and potentially controversial (esp. when maintaining backwards compatibility).

**Comment by brollb** [comment]
Closed as the correct fn call returns the expected number of ids
