### ISSUE TITLE
move custom blocks back to their respective categories (as done in Snap!)

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1183]
in Snap!, custom blocks are loaded into their given categories. This behavior should be restored in netsblox

**Comment by hamidzr** [comment]
what changed?

**Comment by hamidzr** [comment]
should we bring back the "other" tab instead of the custom tab?

**Comment by brollb** [comment]
Hmmm...  There was actually done positive feedback about this category... We might have to think about this some more
