### ISSUE TITLE
If no movie poster found, return empty image (MovieDB)

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1231]

**Comment by ellienguyen** [comment]
To get the movie poster, we have to get the path and pass it on to getImage. So what you mean is if we pass a blank string or invalid string to getImage, we return an empty image?

**Comment by hamidzr** [comment]
if we wanna send an empty image as error, we should be consistent and change the apiconsumer's sendImage to handle errors like that
