### ISSUE TITLE
custom blocks for viewing the msg buffer on the client

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1271]
It also would be good to be able to clear these and such

**Comment by brollb** [comment]
We have some basic blocks for viewing and clearing the msg buffer. These will work for now but I think there could be a better way to design these...
[msg-buffer-blocks.zip](https://github.com/NetsBlox/NetsBlox/files/1112143/msg-buffer-blocks.zip)

**Comment by ellienguyen** [comment]
@brollb Is that possible that we can showing a list of messages with more information like what fields it has,.. ?

**Comment by brollb** [comment]
Not easily. The problem is that there is not just a single message buffer; each message handler has its own buffer of queued messages. We could expose these queues but then it would make the blocks a bit more complicated and I am not sure of a good way to reference the queue of a specific message handler...

Does that make sense?

**Comment by brollb** [comment]
We could merge all the queues and try to create message structs but this could be problematic as a message could show up twice and it might give the user the feeling that this list of message structs is the message buffer and could give the user the feeling that editing the list will edit the messages in the buffer (which would not be the case).

**Comment by brollb** [comment]
These blocks have been posted in the forums (http://community.netsblox.org/topic/13/blocks-message-queue-editing-blocks)
