### ISSUE TITLE
Cannot send a custom block in an rpc call

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1278]
![rpc-fn-call](https://user-images.githubusercontent.com/4982789/27688757-66ae226e-5ca1-11e7-92f2-a4db7c81ea31.png)

These blocks should be serialized (xml) and then sent to the server.

This will be necessary for #1152

**Comment by hamidzr** [comment]
#1284

**Comment by brollb** [comment]
This has been fixed
