### ISSUE TITLE
active room not found on save

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1295]
Sometimes the user seems to lose the given room... It seems that the room's uuid gets overwritten.

It would be good to refactor this into a `register` method in the RoomManager to make sure the room doesn't exist. I suspect there is a race condition in `getRoom`.

**Comment by brollb** [comment]
It actually looks like `_room` is undefined in the `saveProject` route... this is pretty strange. It would be nice if we knew how to reproduce this...

**Comment by hamidzr** [comment]
> It would be good to refactor **this** into a register method in the RoomManager 
what do you mean by **this**

**Comment by brollb** [comment]
My bad. I meant that the registration of the room should be in a `register` method which first verifies that it isn't overwriting an existing room.

**Comment by brollb** [comment]
This is no longer an issue. Saving is now independent of the room state and websocket connection (tests are in the client submodule).
