### ISSUE TITLE
open public project does not work in non-english language

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1297]
When opening a public project, if the language is set to a non-english language, the project will not open.

@hamidzr do you mind looking into this?

**Comment by hamidzr** [comment]
Is this present in production? I'm trying to reproduce this by
1. changing the lang in editor
2. going to netsblox.org and opening a published project
and it works.

**Comment by hamidzr** [comment]
Do you get any sort of error? or message?

**Comment by brollb** [comment]
I didn't see any error or message... I will try to recreate it and put more details up here when I do.

**Comment by brollb** [comment]
Yeah, I can't reproduce this again...
