### ISSUE TITLE
changing the rpc field when inputs are in the block can create black shadow

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1298]

**Comment by hamidzr** [comment]
this happens every where, it's not limited to customblocks 
![shadow](https://user-images.githubusercontent.com/12127420/28037613-889c002e-6581-11e7-8ce2-b22eb000574d.png)

**Comment by hamidzr** [comment]
this stems from the problem that the input stays around after changing the rpc method to sth else thus referring to an input that no longer exists.
when removing the variable, the block tries to reset the input hint and throws an error.
