### ISSUE TITLE
failing test from RPC Manager

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1305]
There is a failing test related to `supertest` and/or RPC Manager. What is unusual it is inconsistent in showing up. 

our supertest is a devdependency at version 1.0.1. the latest available is 3.0 

`Server Tests RPC Manager Tests RPC tests "after each" hook for "should return 400 if bad action":
     Error: expected 200 "OK", got 401 "Unauthorized"`

**Comment by hamidzr** [comment]
this makes the Travis results show a failing build when it's not.

**Comment by hamidzr** [comment]
bumping the supertest version seems to solve it but we have modules depending on the older version.

**Comment by brollb** [comment]
what depends on the older version?

**Comment by hamidzr** [comment]
I don't know. but since we don't have it in our package.json file means that we didn't ask for this package but it was installed because it was a dependency of another package, right?

**Comment by brollb** [comment]
it is in the json (devDependencies). However, updating supertest didn't seem to fix it (https://github.com/NetsBlox/NetsBlox/pull/1351). I will keep digging
