### ISSUE TITLE
message creation dialogue is missing a left arrow to remove arguments

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1309]
when creating messages one should be able to remove all the arguments to create a message with no payload. ( it is technically possible right now but the UI should support it too )

**Comment by brollb** [comment]
so, messages without a data payload can be created - any empty fields are ignored when creating the message type. We can still change the UI so that the field can be removed, but I would say this is a low priority

**Comment by brollb** [comment]
This has been fixed (awhile back, actually)
