### ISSUE TITLE
need for historic temperature readings/data

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1313]
we need access to historic temperature data from the path that the upcoming eclipse is taking. 
one option is to save it ourselves from what we are getting through openweathermap, the other option is to rely on external sources. ( Are there any free and accurate ones )

**Comment by hamidzr** [comment]
@brollb What do you think about this one? Should I store all the calls to the weather channel in mongo? (alongside timestamp and loc for the call)

**Comment by brollb** [comment]
Check out the details for https://openweathermap.org/history

**Comment by hamidzr** [comment]
yea I did, doesn't come free tho. What we are mostly interested in is to observe and log the changes in temperature (for future use) caused by the upcoming eclipse during its travel through the states.

**Comment by brollb** [comment]
I think we can close this now, right? @hamidzr

**Comment by hamidzr** [comment]
definietly.
