### ISSUE TITLE
the rpc path should be always lowercase

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1315]
is this sth that we should have? if the service name is *WeatherMap* should the path be *weathermap* or *WeatherMap*?

**Comment by brollb** [comment]
The rpc path should probably just be created automatically by the rpc manager and should not depend upon a `getPath` function. This should simplify the source code. To stick to conventions, we could have the path inferred from the rpc dir structure. The service name could then be the dir name converted to upper camelcase.

for example, `google-maps/` would create a service named `GoogleMaps` and a path of `google-maps/`.

**Comment by brollb** [comment]
The rpc path should probably just be created automatically by the rpc manager and should not depend upon a `getPath` function. This should simplify the source code. To stick to conventions, we could have the path inferred from the rpc dir structure. The service name could then be the dir name converted to upper camelcase.

for example, `google-maps/` would create a service named `GoogleMaps` and a path of `google-maps/`.

**Comment by brollb** [comment]
In other words, it should probably be consistent as we can generate the rpc path and then can simplify creating rpcs by not requiring the `getPath` function. Other than that, it really isn't a big deal bc it isn't publicly exposed.

**Comment by hamidzr** [comment]
That's true, I was updating ApiConsumer and was thinking that we can have it there but we can also have it a level higher ( in rpcmanager ). 
> Other than that, it really isn't a big deal bc it isn't publicly exposed.

So it wouldn't break anything if it is changed for older RPCs right?

**Comment by brollb** [comment]
As of #1363, `getPath` is no longer required for RPCs and the path is just created from the rpc name which is inferred unless there is a field called `serviceName` defined in the given service (such as for NASA and MovieDB).
