### ISSUE TITLE
rework staticmaps

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1333]
#1331

**Comment by brollb** [comment]
Can you add more detail here about what the issue is?

**Comment by hamidzr** [comment]
I basically made this issue since we decided to split PR #1331 to 2 PRs.

refactor staticmaps to extend ApiConsumer which comes with disk caching and better-organized code

maybe add two methods to the service (getXY and getLatLon)

clean up the code for better maintainability.

**Comment by brollb** [comment]
I don't think this is still an issue, is it?

**Comment by hamidzr** [comment]
What I meant by rework was to have it go through APIconsumer update caching
and cleanup the codebase.
