### ISSUE TITLE
"help" content for services

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1362]
When using a "call rpc" block, right clicking and selecting "help" should provide information about that specific service or rpc. Ideally, some of this content can be generated dynamically on the server from the rpc source code (maybe jsdoc?)

**Comment by hamidzr** [comment]
we should break this down to sub-tasks. ( feel free to add/edit )
- [ ] pick a js parser
- [ ] add JsDoc style comments to RPCs 
- [ ] extract, parse the comments and attach to the RPC function
- [ ] parse, validate and enforce types in RPC manager. provide feedback to the user
- [ ] inform the user of this metadata: variable types, defaults,  whether they are optional, descriptions, and expected values.

**Comment by hamidzr** [comment]
I'm moving the first 3 tasks to a new issue https://github.com/NetsBlox/NetsBlox/issues/1605

**Comment by hamidzr** [comment]
the second part was done in #1611

**Comment by brollb** [comment]
This has been added (although not all the services have documentation at the moment!)
