### ISSUE TITLE
Allow blocks to connect after the `send response` block

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1379]

**Comment by hamidzr** [comment]
what prompted this change?

**Comment by brollb** [comment]
we discussed this in the meeting. Basically, this made sense initially when we were calling them "request-reply" as this seems to imply that the purpose of the request is to send the reply (hence it being like a `report` block). However, when these are just sending a response to a block which is just sending a msg and waiting, the same implication isn't there (or at least isn't quite as strong).

That is, `send msg and wait` could just be waiting for coordination reasons and not because it is requesting a value. Since its purpose isn't just to request a value, the response block is less like a distributed `report` and more like another possible action.
