### ISSUE TITLE
rpc inputs can't handle different forms of lists

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1439]
anything other than simple hand-coded list

**Comment by brollb** [comment]
Can you upload an example that demonstrates this bug?

**Comment by hamidzr** [comment]
yeah looks like I didn't do enough testing. it is working on master right now.. I'm looking into it.

**Comment by brollb** [comment]
no worries. I was puzzled bc they should be handled the same

**Comment by hamidzr** [comment]
would you add what you found yesterday here?

**Comment by hamidzr** [comment]
I added a dev service with an echo rpc and in this project I'm demonstrating the bug. 
[inputBug.xml.zip](https://github.com/NetsBlox/NetsBlox/files/1257598/inputBug.xml.zip)
