### ISSUE TITLE
Project export hangs without exporting

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1518]
Sometime the project export shows the "Exporting" message but never actually exports the project. I suspect there is an error on the server.

This should be investigated more but one easy workaround for simple (single role) projects would be to export these locally w/o server support. This wouldn't fix the essence of the issue but would make it less apparent

**Comment by brollb** [comment]
The server should also report an error if it encounters one during export and we should try to find a way to recreate this

**Comment by brollb** [comment]
I think this is related to #1898. We will see if the issue still happens...

**Comment by ToonTalk** [comment]
If I have a second role then export project says it is exporting but a file dialog box never appears. If I delete the second role and try again then it exports as normal.

**Comment by brollb** [comment]
This should no longer be a problem as timeouts have been introduced semi-recently.

For a little more background, exporting a project can be a little bit tricky as it attempts to get the latest version (not just the last saved version) of all the roles. Since only a single role is loaded at a time (by the client viewing/editing it), this means that the latest state of the role may need to be requested from the connected clients. At the time of this issue creation, I believe there was some missing error handling around flaky connections to the clients. That is, there was poor handling of a failed request for the latest role state. This has since been improved. If this occurs again, we can open a new issue (referencing this issue).
