### ISSUE TITLE
make login cookies accessible to frontend

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1523]

**Comment by hamidzr** [comment]
this issue  has one more part left from previous PR. httpOnly flag has to be removed

**Comment by hamidzr** [comment]
This has an implication that needs to be discussed.

**Comment by brollb** [comment]
Removing the `httpOnly` flag would cause some security issues with custom js blocks

**Comment by brollb** [comment]
Since this exposes a security issue, I am going to close it.
