### ISSUE TITLE
netsblox.org (including editor.netsblox.org) site down

### ISSUE THREAD

**Issue by petermmiller** [NetsBlox/NetsBlox#1525]
The [netsblox.org](https://netsblox.org) site (including [editor.netsblox.org](https://editor.netsblox.org)) has been down for approximately 12h.

- netsblox.org returns HTTP ERROR 500 - Internal Server Error.
- editor.netsblox.org appears to timeout while serving netsblox-build.js, after sending 48.4K.

**Comment by brollb** [comment]
Thank you for the heads up! It should be fixed now.
