### ISSUE TITLE
ThingSpeak "limit" doesn't seem to work as expected

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1544]
![snap0016](https://user-images.githubusercontent.com/4982789/30697670-6c8edf52-9ea5-11e7-8430-acd2a70a0293.png)

**Comment by hamidzr** [comment]
If I'm not mistaken the server gives us the response back in pages of 15, and thus to not throw away the results she is returning em in chunks of 15. But with the caching that we have this behavior doesn't add any benefit
