### ISSUE TITLE
bad reading in eclipse data

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1585]
there is a moon icon showing up during the eclipse simulation. It is due to a corrupt reading returned by weatherunderground servers.

**Comment by hamidzr** [comment]
![deepinscreenshot_select-area_20171005102254](https://user-images.githubusercontent.com/12127420/31235978-6ced98d0-a9b8-11e7-89cb-4015322c0b00.png)

**Comment by brollb** [comment]
The bad data point has been removed
