### ISSUE TITLE
shadow in eclipse visualizer leaves the path

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1594]
happens on slower networks.
reproduce: 
- set the network preset to "fast 3g" through chrome dev tools
- start the project and wait
- hit play

**Comment by hamidzr** [comment]
#1597 should help this situation,

**Comment by hamidzr** [comment]
the update project [eclipse.zip](https://github.com/NetsBlox/NetsBlox/files/1459178/eclipse.zip)

**Comment by brollb** [comment]
@hamidzr this has been fixed, right?

**Comment by hamidzr** [comment]
Yes, that was a problem which does up in slow networks. We dinner it by
batching some rpcs

On Jan 17, 2018 11:40 AM, "Brian Broll" <notifications@github.com> wrote:

@hamidzr <https://github.com/hamidzr> this has been fixed, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NetsBlox/NetsBlox/issues/1594#issuecomment-358383269>,
or mute the thread
