### ISSUE TITLE
too many server requests for googleMaps

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1596]

**Comment by brollb** [comment]
Can you expand on this?

**Comment by hamidzr** [comment]
often times with googlemaps the usage pattern is that we need both x and y coordinates ( eg to display items on the map ) and right now the RPC doesn't provide a single call to accommodate that. Since Google maps is used in many projects it would be good to have such a cal to speed up the projects and reduce the number of requests.
