### ISSUE TITLE
services and RPCs should support annotations for descriptions, type info, etc

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1605]
- [x] pick a js parser and doc standard. ( doctrine & google closure ? )
- [x] add JsDoc style comments to RPCs as a test
- [x] extract, parse the comments and attach to the RPC function

**Comment by brollb** [comment]
I commented on the PR: https://github.com/NetsBlox/NetsBlox/pull/1610

I was thinking that it might be nice to add something concrete that affects netsblox or the development of rpcs into this issue because currently the parsed jsdoc isn't used at all. I might update the issue name accordingly after we have something more concrete.

**Comment by hamidzr** [comment]
I'm working on putting it to use. at this point:
- send docs to client side
- construct the rpc arguments using the docs
- validate and more #1362

**Comment by hamidzr** [comment]
do we want to be able to set the function name rpc name different from the actual function name? @brollb 
I think in jsdoc we should have both `@name` and `@fnName` then if we want to manually set the associated function we use fnName. This will leave @name free to be used as a caption for RPC name

**Comment by brollb** [comment]
The description should be enough, shouldn't it? Do you have an example where `@name` and `@fnName` should differ?

**Comment by hamidzr** [comment]
isn't the difference kind of the reason we introduced compatibility?

**Comment by brollb** [comment]
These are actually a couple different issues. The description for a method should be able to be used for the `help` message in the future (not right now). `COMPATIBILITY` is used to ensure backwards compatibility such as converting to old method signatures.

However, I don't see why we would need to add `@fnName` (as it seems independent of the description for the method - which we already have in the jsdoc). As far as compatibility, we can support the old method and then just deprecating it so old calls to it still work. 

Am I missing something?

**Comment by hamidzr** [comment]
if we have the @name and the displayed RPC names come from the name param then we wouldn't need to ever change the actual RPC function name and wouldn't need backward compatibility right? 
However, the current way is alright so we don't need fnName. I updated the PR it should be fine

**Comment by hamidzr** [comment]
one question remains
what happens to a jsdoc  that doesn't set the parameter type?

**Comment by brollb** [comment]
If there is no type specified, it might be nice to print a warning on start. The server will just not do any casting for the given input

**Comment by hamidzr** [comment]
alright
