### ISSUE TITLE
googlemap coordinates go out of bound at international line

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1617]

**Comment by brollb** [comment]
Is this something that should be handled by the GoogleMaps service or the NetsBlox application?

**Comment by hamidzr** [comment]
it's a situation internal to the service, so i say googlemaps

**Comment by brollb** [comment]
That makes sense - I was thinking that this was saying that it should accept invalid latitude/longitude values.

Good catch - PR has been merged.
