### ISSUE TITLE
compatiblity issues with LWIP package

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1651]
incompatible with node 8
build issues on different platforms

blocking:
- mocha chrome > client side tests in CI

**Comment by hamidzr** [comment]
In order to support mocha chrome we need to update Travis to use node 8.9 that means we probably should move to node 8 before moving in with mocha chrome

**Comment by brollb** [comment]
It looks like this fork of lwip supports node 8: https://github.com/mixer/lwip

**Comment by hamidzr** [comment]
some alternatives could be 
- https://github.com/oliver-moran/jimp
- https://github.com/lovell/sharp
