### ISSUE TITLE
Remove public-projects collection?

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1652]
The public-projects collection made sense initially as the projects were nested inside user documents. However, with the creation of the projects collection, we could just use that data.

Note: this doesn't need to be removing the `src/server/public-projects.js` file. It would just be changing the implementation to query from the regular projects collection and add `Public: true` to the queries.

**Comment by hamidzr** [comment]
makes sense, and since there shouldn't be any changes to the public API we shouldn't have any problems. I would just check to see if is breaking anything on the landing page

**Comment by brollb** [comment]
This was also recently causing a minor issue with the images displayed when sharing links on facebook so I am going to prioritize it a bit.
