### ISSUE TITLE
users still logged in after "successful" logout

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1682]
this problem is especially visible when the authentication system is used in other places like frontend, mobile app or teacher dashboard

What's tested ? 
- `logout` endpoint's response is received from the server with header `Set-Cookie:netsblox-cookie=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT` and body `you have been logged out`
- after logout browser cookies are still present with original content (details linked below)
[editor cookie details](https://user-images.githubusercontent.com/12127420/33090190-bd29d1ae-ceb8-11e7-9ebc-dd391f6c2562.png)  [frontend cookie details](https://user-images.githubusercontent.com/12127420/33090191-bd3b3dea-ceb8-11e7-9835-bc2e71591dc7.png)

**Comment by hamidzr** [comment]
`  netsblox:api:Users:log undefined has logged out +0ms` session.username appears to be undefined at the time of logout

Question: why isn't login defined in `routes/users` like logout and the rest of user routes

**Comment by hamidzr** [comment]
started a branch with some log statements. 1682

**Comment by brollb** [comment]
This seems to be related to the specific deployment and the originating subdomain. The response from the server seems to be correct but the browser isn't clearing the cookie...

**Comment by hamidzr** [comment]
same behavior in firefox

**Comment by hamidzr** [comment]
solved in #1992
