### ISSUE TITLE
isActive pending request and issue with saving the project

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1778]
- `isProjectActive` sometimes times out
- ~~`saveProject` fails with an error: to reproduce: 1. open a project 2. edit 3. save~~
- opening from URL, editing and then saving results in saveProject error: ![ss](https://i.imgur.com/qrKzdG9.png)

**Comment by brollb** [comment]
I think `isProjectActive` is probably due to duplicate rooms being stored on the server and slowing down some of these queries...
