### ISSUE TITLE
accepting invitations request breaks appmode

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1786]
re-enabling `appMode` after the project is loaded fixes this problem.
 required for accepting invitations in mobile devices

**Comment by brollb** [comment]
What do you mean by "breaks" app mode? Do you mean that it exits app mode?

2017. dec. 19. du. 4:32 ezt írta ("Hamid Zare" <notifications@github.com>):

**Comment by hamidzr** [comment]
I'll post an screen shot, basically the page ends up looking half loaded

On Dec 19, 2017 4:56 PM, "Brian Broll" <notifications@github.com> wrote:

What do you mean by "breaks" app mode? Do you mean that it exits app mode?

2017. dec. 19. du. 4:32 ezt írta ("Hamid Zare" <notifications@github.com>):

> re-enabling appMode after the project is loaded fixes this problem.
> required for accepting invitations in mobile devices
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=
https%3A%2F%2Fgithub.com%2FNetsBlox%2FNetsBlox%2Fissues%2F1786&data=02%7C01%
7Cbrian.broll%40vanderbilt.edu%7Cf487e135cf954425360608d547303e40%
7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636493195012194710&sdata=
mSzLRlZKGoPsi7%2ByysLFmlDVbCnKcnArR9x2EaXNCzk%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=
https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-
auth%2FAEwIBVpBOUGZ3q6_VEDUaZCuZGUBL5KMks5tCDlKgaJpZM
4RHpeW&data=02%7C01%7Cbrian.broll%40vanderbilt.edu%
7Cf487e135cf954425360608d547303e40%7Cba5a7f39e3be4ab3b45067fa80fa
ecad%7C0%7C0%7C636493195012194710&sdata=eZS1C5oEDD%
2BkgB1hJ4cPutkzoVw5go5l0Xj5efS2JZY%3D&reserved=0>
> .
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NetsBlox/NetsBlox/issues/1786#issuecomment-352912274>,
or mute the thread

**Comment by hamidzr** [comment]
![ss](https://github.com/NetsBlox/netsblox.org/pull/86)

**Comment by hamidzr** [comment]
`nbMorph.toggleAppMode(true);` fixes the issue after the project is loaded.

**Comment by hamidzr** [comment]
moving from one role to another while in appMode also has the same effect
