### ISSUE TITLE
additional roles are not loaded

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#1794]
roles other than the main role are not ~~saved~~ and/or loaded on master
reproduce:
1. open a project 2. create two roles, 3. save 4. reload 5. open project 
or 1. open pong example 2. go to # 3 in the process above.

**Comment by brollb** [comment]
Only on master, right? Not on stable?

2017. dec. 21. 11:20 ezt írta ("Hamid Zare" <notifications@github.com>):

**Comment by hamidzr** [comment]
Correct
