### ISSUE TITLE
Add RPC for gettting historical stock quotes

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#1884]
The IEXTrading service should also support getting historical stock quotes.

**Comment by brollb** [comment]
@dtryan24

**Comment by gsteinLTU** [comment]
I'll take a shot at this.

**Comment by gsteinLTU** [comment]
Can you tell me if 9e31c0713a36f99027884efebddc248fd3591284 is the kind of thing you're looking for? After working on it, I realized there are a lot of options for handling this data.

**Comment by brollb** [comment]
Yeah, that looks great! Feel free to make a PR and we can start working on getting it merged!

**Comment by brollb** [comment]
One minor thing that will need to be added before merging will be a test for the interface (we have tests for the RPC method signature to ensure that we don't break backwards compatibility): https://github.com/NetsBlox/NetsBlox/blob/master/test/unit/server/rpc/procedures/iex-trading.spec.js

It should be pretty straight-forward but if you have any questions, don't hesitate to ask!

**Comment by brollb** [comment]
It works quite nicely with the charting service:

![deepinscreenshot_google-chrome_20180330074809](https://user-images.githubusercontent.com/4982789/38138131-b5637740-33ee-11e8-979b-ae6758cdc469.png)

Looking forward to getting it integrated!

**Comment by gsteinLTU** [comment]
Got it together, I'm sending the PR now.
