### ISSUE TITLE
Poor error handling importing Snap! project using "tell"

### ISSUE THREAD

**Issue by ToonTalk** [NetsBlox/NetsBlox#2024]
![image](https://user-images.githubusercontent.com/2138696/40114456-e5242c3c-5904-11e8-999e-2656158e5912.png)

The Snap! control primitive "tell" is missing from NetsBlox. Importing a project using it (or other missing primitives) should at least produce a helpful error message.

**Comment by brollb** [comment]
I believe this should be fixed now and simply replace the block with an "obsolete" block. Feel free to re-open or create a new issue if you are able to repro. ("Tell" is now part of netsblox so it will need to be reproduced differently.)
