### ISSUE TITLE
What is best practice for zero-argument message type?

### ISSUE THREAD

**Issue by ToonTalk** [NetsBlox/NetsBlox#2031]
For example

![image](https://user-images.githubusercontent.com/2138696/40244927-186971f2-5abc-11e8-80da-eb76779e68b2.png)

The other player just replies with a boolean. What should I put in second slot? Clearly it doesn't matter but it does clutter up the code both sending and receiving.

Perhaps this could work like "list" where it has an argument but you can get rid of it to create an empty list.

**Comment by brollb** [comment]
Yeah, that might be nice to add. Currently, any blank fields are not included in the message so leaving that field blank will result in a message without any data payload/fields.

**Comment by brollb** [comment]
This has been fixed and the fix is available in the deployed version of netsblox!
