### ISSUE TITLE
Import project doesn't create roles

### ISSUE THREAD

**Issue by ToonTalk** [NetsBlox/NetsBlox#2048]
I created a second role, exported the project, closed the tab, launched NetsBlox, imported the project, and there is only one role. The project XML does include the second role.

**Comment by brollb** [comment]
Can you reproduce the issue with the given xml? If so, do you mind sharing it so I can look into it? Of course, I will check it out regardless but it always helps when it can be reproduced.

Thanks for reporting it!

**Comment by ToonTalk** [comment]
Here it is.
[untitled.zip](https://github.com/NetsBlox/NetsBlox/files/2034334/untitled.zip)

**Comment by brollb** [comment]
After looking at the xml, I don't see any content for the second role (I see that there is a second role called "test" but I don't see any associated content). When you created the project, did you move to the role and edit it or only create a new role and then immediately save/export?

**Comment by ToonTalk** [comment]
I only created it but I assumed that then importing it would also just create it.

**Comment by brollb** [comment]
I agree that it should - I just wanted to make sure that I understood the scenario so I could reproduce it!
