### ISSUE TITLE
Roboscape clarification and feature request about ticks

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2068]
@mmaroti  After thinking about how we can compute the location of the robot using ticks with Brian I have a question and a potential feature request.

1. Do the ticks ever go negative? are they reduced when the wheel turns the opposite direction?

2. What do you think about having status reports in the form of tick status messages from the robot right before it starts executing a new movement command (or maybe any command)?

**Comment by mmaroti** [comment]
@hamidzr Can you please investigate 1? After the cyber security camp with can update all software to report ticks for each responses (we currently report only the time in milliseconds when the command was executed).

**Comment by hamidzr** [comment]
Sure I'll look into it

**Comment by mmaroti** [comment]
@hamidzr Maybe it would be enough to report the ticks automatically for every "set speed" command and not for all commands. That is less radical change. What do you think?

**Comment by hamidzr** [comment]
Yes, that is what I initially had in mind. As long as we have the tick messages for every command that could affect the robots' trajectory we should be able to locate it. Since `set speed` is the only such command that should work. One would say the user could request the ticks whenever it hears that `set speed` command was initiated but there would be a delay. 

Although we have to consider the number of messages this would add to the network. People might have set speed in a forever loop. Could this be a problem? Maybe this could be a configurable parameter in the `listen` command

for number 1: whenever the wheel rotates CCW the number of ticks keeps going down and it can also go negative.
