### ISSUE TITLE
Export to Snap! has error when importing to Snap! (master only)

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#2218]
This only occurs on master afaik. Exporting to Snap! still includes the RPC error watcher info and Snap! just throws an error if it encounters an unsupported watcher during load. We should remove the watcher info from our serialized content when exporting to Snap!.

**Comment by hamidzr** [comment]
closed in https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/commit/09e40a17acc027bc606a20694a660576c7cb54ec
