### ISSUE TITLE
roboscape mode "both"

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2223]
crashes the server
1. listen to robot x
2. get range robot x
![](https://i.imgur.com/AE2EbBR.png)

**Comment by brollb** [comment]
It would be nice to update the error to show the error from the actual code (without the extra log). Not a big deal though since I believe `content` is used on the next line.

**Comment by hamidzr** [comment]
right, I screeneshotted at the wrong part.

**Comment by hamidzr** [comment]
fixed by #2251
