### ISSUE TITLE
room roles can be stale in initial state update

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2242]
when loading a project fast through the [anchor links](https://dev.netsblox.org/?action=example&ProjectName=Dice) 
room receives a state without the proper roles.
![](https://i.imgur.com/ITPQVEO.png)

`room.getCurrentRoleName` and `room.getRoles` and therefore `room.getCurrentOccupants` are in disagreement

**Comment by hamidzr** [comment]
in one instance the after opening the dice project correct state was received but afterwards  an older state (from new project) was received with higher version

**Comment by hamidzr** [comment]
this happens on dev running `f7fdca70e057d7356be7dabe26c0abd84bd44546` which is the latest on master.
I have not seen this happen on our local cloud env or local machine with or without network throttling

**Comment by brollb** [comment]
Moved to https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/issues/728

**Comment by hamidzr** [comment]
fixed in https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/commit/e062e7afe3753e52d83edb1bfe0f052854e5353a
