### ISSUE TITLE
Translation RPC with better caching

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/NetsBlox#2256]
Right now repeated requests for translations aren't cached properly. We can do this in an elegant way if we can make the GUID for the request out of a hash of the text and languages. #2253 was just for the translation feature in general. 

We also might need to talk about how much actually should be cached and for how long.

**Comment by hamidzr** [comment]
an option is to override `_getCacheKey`

**Comment by gsteinLTU** [comment]
#2260 has the fix for this.
