### ISSUE TITLE
Credentials issue for Translation RPC

### ISSUE THREAD

**Issue by CliffordAnderson** [NetsBlox/NetsBlox#2271]
The Translation RPC is currently throwing a 401 error whenever I try anything other than `getSupportedLanguages`. 

![translation](https://user-images.githubusercontent.com/1919466/48361428-17cb0080-e667-11e8-9760-224ec77a3cd1.png)

I assume this must be a problem with the credentials on the backend. Thanks for taking a look!

**Comment by gsteinLTU** [comment]
Thanks, we were using my Azure account and it looks like they don't automatically change from the free trial to pay-as-you-go.

**Comment by gsteinLTU** [comment]
The service should be working now, although for a little while it may be only partially working as our subscription doesn't seem to be fully transferred to the new payment plan.

**Comment by CliffordAnderson** [comment]
@gsteinLTU Yes, I can confirm it's working for me now. Thanks for the quick solution!
