### ISSUE TITLE
user requested action without project

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2322]
3 potentially related error logs
```
netsblox:network-topology:warn Could not set client state for _netsblox1547482542429
netsblox:network-topology:error Could not find socket: ausername
netsblox:client-3684:error User requested actions without project: 
```

**Comment by brollb** [comment]
The last log (also in the name of this issue) should not be able to happen anymore as the project ID is sent in the request and does not rely on the socket's state on the server.
