### ISSUE TITLE
rpc manager should handle `Exception` and `Errors` differently

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2350]
expose error.message bug not exception.message (show: something went wrong)

**Comment by brollb** [comment]
I really don't like opaque error messages like this. I would strongly prefer trying to come up with a more general version of `rewordError` that is used to provide more meaningful errors. This could also be incorporated into APIConsumer to handle some standard status codes (like 403, etc). This should be able to be overridden by the user, of course.

**Comment by brollb** [comment]
What motivated this issue? Were there complaints or issues with students in the classroom? Or was it simply preventative?

**Comment by hamidzr** [comment]
if I recall the main motivation was to 
- not show uncaught errors to users and show a friendlier catchall version
- show errors that the service decides to show
