### ISSUE TITLE
there is no access control over roboscape's robots

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2351]
anyone with access to nestbox can talk to the robots

**Comment by hamidzr** [comment]
- [ ] persistent storage for ACLs 
- [ ] change service to lookup ACLs
  - [ ] cache?
  - [ ] regulate access
- `getRobots` to show all accessible robots to the caller

**Comment by hamidzr** [comment]
access to the service should be regulated on these fronts:

- access lists should get updated w/o need for a server restart

- all the RPC calls to the service
  - `getRobots` returns only authorized robots
  - includes robot actions and listen, changing keys, etc
- incoming message from robot
- previously registered robots (eavesdrop)

**Comment by hamidzr** [comment]
should let the current robots keep working. meaning if there is no record of the robot in the database, assume it is public

**Comment by hamidzr** [comment]
separare required features could include: 
- a way creating custom routes for services

**Comment by brollb** [comment]
@hamidzr - I believe this has been addressed entirely, right? Are there any remaining features to be added or can this be closed?

**Comment by hamidzr** [comment]
I think we have addressed this
