### ISSUE TITLE
potential gnuplot compatibility issues

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#2392]
chart service isn't working on windows. Also due to Buffer deprecation in node 10 there are issues with that version of node and chart service

**Comment by brollb** [comment]
This is referring to when netsblox is deployed on windows, right?

If so, why do we need to deploy on windows? Is using docker an issue?

**Comment by hamidzr** [comment]
we have a student working on a service and for an example project, they want to use the charting service and ran into the issue.

**Comment by brollb** [comment]
So the student is running netsblox locally on a Windows machine? What about running it with docker (sharing the files so they can still be developed in Windows)?

**Comment by hamidzr** [comment]
right, I think that is what windows users (and maybe all users) should do

**Comment by brollb** [comment]
Do we have public documentation about how to set this up? Might be good to have to point to
