### ISSUE TITLE
Ease of use improvements for Chart RPC

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/NetsBlox#2418]
Related to #2417, Akos noted that the Chart RPC requires a few extra (and non-obvious) steps to plot the data, and he'd rather have it be able to directly plot the output.

Addressing #2261 eventually may cause an issue with this (but it would likely break a lot of projects in the same case).

**Comment by gsteinLTU** [comment]
Testing it more, it should detect if gnuplot isn't set up and not be enabled. Right now it just fails with no error or output in that case.

**Comment by brollb** [comment]
Fixed by https://github.com/NetsBlox/NetsBlox/commit/6711b2be5d4485b7a8ae05281fbe96d0c0757a9e
