### ISSUE TITLE
Incorrect mixed use of "async" and callback in server's `start` method

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#2424]
The `start` method for the server is incorrectly using both the `async` keyword (which uses promises) and a callback, `done`. It seems that this was introduced [here](https://github.com/NetsBlox/NetsBlox/commit/68462d8d8e5ba1e9943f0c88be81a20c218980af#diff-f286c15f5cb962ed226f2aae653ca1cfR283) when the method was changed to async without removing the usage of a callback.

**Comment by hamidzr** [comment]
good catch how did you run into it?

**Comment by brollb** [comment]
I ran into it when I was looking at the codebase. Thankfully, the usage of `start` wasn't updated anywhere to use async/await so the bug wasn't exposed (yet!) :smile:
