### ISSUE TITLE
Large datasets eat up stack

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/NetsBlox#2426]
@IsmailHabibi and I have had this issue with work on #2420 and #2415. Returning large amounts of data from an RPC will result in an exception: "RangeError: Maximum call stack size exceeded".

**Comment by gsteinLTU** [comment]
This may be on the client side on second thought, it seems like the data is making it across and no errors are in the logs.

**Comment by brollb** [comment]
Fixed by https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/885
