### ISSUE TITLE
Roboscape robots should have some good default wifi settings

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/NetsBlox#2439]
As the provisioning app does not work for all devices and the web interface for the setup may be difficult to understand/access for some users, the robot firmware should detect that the module is not configured and reset it to the robonet AP settings. This also prevents accidental setup mode activations in camps from requiring an app to fix.

**Comment by hamidzr** [comment]
fixed in https://github.com/NetsBlox/NetsBlox/pull/2440
