### ISSUE TITLE
Add service documentation (and alpha notation) to NYPL, Smithsonian

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#2869]
The New York Public Library and Smithsonian services should be marked as alpha and should have service documentation like [this](https://github.com/NetsBlox/NetsBlox/blob/master/src/server/services/procedures/base-x/base-x.js#L1-L7).

For now, they probably don't need a category though it would be good to add one sometime.

**Comment by brollb** [comment]
@dragazo - Do you mind taking care of this?

**Comment by dragazo** [comment]
@brollb Oh sure, I can do that. Thanks for the example.

**Comment by brollb** [comment]
Closed by #2870
