### ISSUE TITLE
Code runs on the selected sprite, instead of the sprite where the script is located

### ISSUE THREAD

**Issue by thomaswp** [NetsBlox/NetsBlox#2885]
**Issue**: When running code in Netsblox, the sprite currently selected in the corral will do all actions (e.g. move, say, etc.), rather than the sprite where the script is, which _should_ be doing these actions.

For example, if I have two sprites: 

**Sprite 1** (gray) with the following code:
![myRole script pic (1)](https://user-images.githubusercontent.com/1750176/95883197-a7442700-0d48-11eb-87fa-d094c958f0f1.png)

and **Sprite 2** (orange) with _no code_...

If I have Sprite 2 selected, and click the green flag, I see this:
![image](https://user-images.githubusercontent.com/1750176/95882123-53850e00-0d47-11eb-845a-faac12029f39.png)

Sprite 2 has said hello, instead of Sprite 1, where the script is.

I've uploaded the test code here (change to .xml):
[test.xml.txt](https://github.com/NetsBlox/NetsBlox/files/5372431/test.xml.txt)

When I first encountered this error, it was with some older code I had loaded, and I got a javascript error (I can't reproduce it). The error was something like: `cannot find target for script`. Which make sense, since the issue is that the wrong script target is being used.

**Comment by brollb** [comment]
Closing this as the problematic code is in the client repo. Updates can be found here: https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/issues/1105.
