### ISSUE TITLE
Twitter API key expired

### ISSUE THREAD

**Issue by thomaswp** [NetsBlox/NetsBlox#2893]
It looks like the API key for the Twitter service is expired. Could you update it? Thanks!

![image](https://user-images.githubusercontent.com/1750176/98302518-86a76f80-1f8a-11eb-9dd6-b69bd1f23d3a.png)

**Comment by brollb** [comment]
Thanks for reporting this, @thomaswp! I will get this updated shortly (and post updates on this issue).

It is worth mentioning that it is possible to provide your own API keys for your user (or your classroom/summer camp) using https://dashboard.netsblox.org. Basically, you can create a group and then add members or API keys. Any members of the group will then use the API keys provided automatically when using a service that depends on the given API key.

**Comment by brollb** [comment]
This should be resolved now! Let me know if there are any other issues!
