### ISSUE TITLE
Auto-generated RPC help pages

### ISSUE THREAD

**Issue by gsteinLTU** [NetsBlox/NetsBlox#3009]
It would be really nice to have an option to open a webpage with a listing of all functions for a service and the respective help content displayed at once.

This will be especially helpful for RoboScape and IoTScape running in "secure" mode. To facilitate these (because they may not be directly callable from the service e.g. "RoboScape/setSpeed [left] [right]" vs "RoboScape/send [robot] set speed [left] [right]") and the listing likely needs to be able to include multiple examples for each function.

**Comment by brollb** [comment]
This has been added! An example of adding custom docs for a service can be found [here](https://github.com/NetsBlox/NetsBlox/blob/3f0c2b0b68a598a5644960a15960edd3086543f0/src/server/services/procedures/alexa/docs/first-steps.rst#L1).
