### ISSUE TITLE
Consolidate documentation (readthedocs?)

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3059]
It would be great to consolidate documentation on NetsBlox. This includes a number of different resources:
- Information hosted on the GitHub wiki
  - developer docs for service creation
  - autograder documentation
  - etc
- Documentation/Help information for services
  - Standard RPC help info
  - Could we add examples?
  - Additional materials and documents should be able to be included, too. (Probably in the services source directory.)
- Walkthroughs and Advanced documentation?
  - Some are hosted on netsblox.org. It might be nice to move them to readthedocs (like in DeepForge).
  - Create your own service? This should probably be in the service documentation actually.

**Comment by brollb** [comment]
@dragazo - Would you mind taking care of this? It would be great to be able to consolidate the existing documentation (from netsblox.org and the GitHub wiki, primarily) and migrate it to the self-hosted readthedocs that you added in #3095. Specifically, I am thinking:
- The [guides from netsblox.org](https://netsblox.org/howtos) should probably be added under a "Step-by-Step Guides" or "Fundamentals" section. I like the organization I used in the [DeepForge documentation](https://deepforge.readthedocs.io/en/latest/) but it may need some modifications since we would like it to still be approachable to teachers and students.
- The [GitHub wiki](https://github.com/NetsBlox/NetsBlox/wiki) should be migrated as well. This *probably* doesn't need too much in terms of updating just yet. Down the road, it would be nice to make portions of it automatically generated as well. Here are my more detailed thoughts:
    - The introduction to dist programming in NetsBlox section is probably largely redundant and covered by the guides on netsblox.org so we can probably skip it.
    - Deployment should probably be its own section in the docs. Probably toward the bottom since it is more of an advanced and less frequently used section. Maybe it would make sense to place it under an "Advanced" section.
    - "Custom Services" should probably be under a "Development" or "Advanced" section. I might prefer "Development" more.
    - The pages under "Custom Autograders" should be made custom docs for the "Autograders" service.
    - "Adding Example Projects" should be under "Development", too.
    - The "Battleship Service" page should be integrated into the Battleship documentation. It may be sufficient to simply update the RPC/Service descriptions.
    - After this has been migrated to the self-hosted documentation, we should put a notification at the top and link to the updated docs hosted on editor.netsblox.org.

**Comment by dragazo** [comment]
Sure, those shouldn't bee too hard to bring over. I think the only thing we might lose are some of the embedded videos I saw on a quick lookthrough, but maybe sphinx has a way to do that anyway. Worst case I can just put a link to the video.
