### ISSUE TITLE
Moving a running receive block breaks messages

### ISSUE THREAD

**Issue by dragazo** [NetsBlox/NetsBlox#3171]
In experimenting with a PhoneIoT project, I found that moving a `when I receive _` block that is running can break in such a way that no more messages are received. I can reproduce this fairly easily if the receive block handler is slow, esp. if it's so slow that messages start to build up. Here's the specific [project](https://editor.netsblox.org/?action=present&Username=devinjean&ProjectName=broken-socket-bug&) I was using.

**Comment by brollb** [comment]
This has been fixed in the client repo. This repo should be closed once the submodule is updated.
