### ISSUE TITLE
Help info about inner types

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3307]
Currently, you can't get help info about inner types from the docs (via a hyperlink). Consider if I want to know about "LineType" below:
![Screenshot_2021-11-16 Chart — NetsBlox documentation](https://user-images.githubusercontent.com/4982789/142062651-b77bdb8f-3df0-4078-bb36-2ba1a95996db.png)

Here, `info` links to the `List` documentation. One approach around this would be to change the formatting so only the argument name is formatted using the "code" styling and the type could actually generate links for both `List` and `LineType`. Thoughts?

**Comment by dragazo** [comment]
Yeah, I think that would work. It'd look a bit weird not having code styling, but that's rst's fault for not having better style orthogonality. The only other detail is that some types have constant (non-type) parameters like `Enum<line,dot>` or `BoundedString<10,16>`, but that can mostly be solved by checking if the constant is the name of a type. We can probably just assume no one will start using `Enum<String,Number>`...

**Comment by brollb** [comment]
I think that sounds good for now. It's pretty unlikely that this will happy; if it becomes a problem, we can address it then.

On the styling front, there are [workarounds](https://stackoverflow.com/questions/45499108/if-possible-how-do-we-put-hyperlink-within-the-code-section-in-rst-files) that should work for getting a similar style with hyperlinks embedded that look promising.
