### ISSUE TITLE
Wordle service

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3352]
It might be nice to have a Wordle service which facilitates a game of Wordle like the Tic Tac Toe game.

**Comment by brollb** [comment]
> Rough idea on RPCs:
> - start game (input: length, optional, default 5) return value: true. It would pick a random n-letter word from the dictionary and keep it a secret
 > - guess (input: n-letter word): false, empty list or error message if not in dictionary, otherwise list of N values: 0 for no hit, 1 for right letter wrong place, 2 for right letter right place
> - give up (no input): secret word

**Comment by gsteinLTU** [comment]
@brollb It would be nice to be able to reuse CommonWords' list for the solutions, but do we have a good source for less common words already? [An existing multi-length variant of it](https://engaging-data.com/wordguessr-wordle/) says they generated word lists from [this source.](https://elexicon.wustl.edu/index.html)

It might also be nice to include the hard mode feature (your guesses must include the parts you already know). Or it, along with the number of guesses, could be left to be enforced in the client program as extra challenges instead.

**Comment by CliffordAnderson** [comment]
I love this idea! There are a lot of WORDLE solvers floating around and it would be a nice exercise to ask students to write a solver in NetsBlox and then test its performance against this RPC. Is that the kind of thing you have in mind?

**Comment by brollb** [comment]
@gsteinLTU - One way to get many words (including uncommon words) would be to use a hunspell dictionary for the language of interest. ([The format looks pretty simple](http://manpages.ubuntu.com/manpages/bionic/man5/hunspell.5.html).) Otherwise, we could increase the number of [common words](https://github.com/NetsBlox/CommonWordsData).

@CliffordAnderson - Good idea! I wasn't thinking about that but it would be possible!

**Comment by gsteinLTU** [comment]
@CliffordAnderson I think the intent wasn't to have the RPC offer a solver, but only the game interface (i.e. generating words and accepting guesses), but that could be interesting. Maybe it could offer some sort of "hint" feature, with longer words it can be difficult to guess at all.

@brollb Are you working on this? I need to take a break from my own project and this seems like something we should get done while Wordle is still in vogue.

**Comment by brollb** [comment]
@gsteinLTU - I am not. Go for it!
