### ISSUE TITLE
Add more explanation about the Object type in RPC docs

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#3434]
A teacher recently asked about what an "Object" was in the RPC docs. It would be nice to add more documentation that makes connections to objects in other languages (like JS, Java, Rust, C++, Python, etc).

**Comment by dragazo** [comment]
Sure, like just in the `Object` entry in input types? Everywhere we refer to `Object` (should) link there, at least.

**Comment by brollb** [comment]
Yep, exactly. It would be nice to flesh it out more [here](https://editor.netsblox.org/docs/fundamentals/rpc-arg-types.html#Object).
