### ISSUE TITLE
A JavaScript function returning a list returns it as a string.

### ISSUE THREAD

**Issue by sofabeddd** [NetsBlox/NetsBlox#3450]
When calling a JS function, if the return value happens to be a list, it returns that list as a string (seen below).
![image](https://user-images.githubusercontent.com/99154463/189975394-30c721c0-f6d0-451c-a85c-072f334956a4.png)

expected behavior:
![image](https://user-images.githubusercontent.com/99154463/189980064-871bdf84-df62-4c58-bad4-55177075ae48.png)

I know in my example that the same could be achieved by splitting my string at each comma, but sometimes that would not work, like if my input string were to have a commas in it (seen below).
![image](https://user-images.githubusercontent.com/99154463/189976919-8d89242c-3253-4ecd-bf0f-ccc0dfde7562.png)
 (actually upon further testing I found that you can't separate strings by a comma)

This would be a very nice feature if implemented, and also useful in certain applications.

**Comment by brollb** [comment]
Can you try wrapping the JS list with `new List(..)`? For example, in the first block, 
```javascript
return new List(string.match(new RegExp(selection, behavior)));
```

**Comment by brollb** [comment]
No worries! Happy to hear you got it figured out :)
