### ISSUE TITLE
<IMPORTANT!> Account Security Vulnerability

### ISSUE THREAD

**Issue by sofabeddd** [NetsBlox/NetsBlox#3451]
While messing with NetsBlox I came across a very serious vulnerability that allows me to log into any account I want to without the use of a password.

For the safety of the public, please email [lucasm93579@mnpsk12.org](mailto:lucasm93579@mnpsk12.org) or [april.collins@mnps.org](mailto:april.collins@mnps.org) with the subject "Lucas | Account Vulnerability Bug Report" for more information.

**Comment by brollb** [comment]
Thanks for reporting this! It has been fixed in https://github.com/NetsBlox/NetsBlox/pull/3461 and editor.netsblox.org has been updated. Thanks again!
