### ISSUE TITLE
FIX YA FORUM!!!!!!!

### ISSUE THREAD

**Issue by 18001767679** [NetsBlox/NetsBlox#3483]
I reported this a long time ago,but just received a thankyou message.
Can you tell me the reason your forum is always 502 bad gateway?

**Comment by brollb** [comment]
Yeah, we had it up again for a while but noticed strange behavior that was causing problems with the main editor. It seems pretty likely that it is malicious though I haven't confirmed this. It will be restored once we can get to the bottom of the issue!

**Comment by 18001767679** [comment]
uh,i mean the forum not the editor
your editor stuffs are fine

**Comment by brollb** [comment]
Ah, sorry for the confusion. The forum was hosted on the same virtual machine as the main editor so, when it looked like it might be under a DoS attack, the main editor was suffering as well.
