### ISSUE TITLE
Unable to invite self to default room

### ISSUE THREAD

**Issue by melvinlu** [NetsBlox/NetsBlox#494]
Oddly enough, sometimes this issue does not occur, although most times it does.

When logged into the default room on two clients with the same account, inviting the other client fails. It will look like it succeeded, but upon viewing the 'room' tab, you can see that it didn't actually go through. And, upon attempting to move to the role that was supposed to be occupied by the other client, you get a "no socket" error window.

**Comment by brollb** [comment]
I believe this was the same issue as #807
