### ISSUE TITLE
'stop' Traffic rpc stops ALL messages

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#603]
If multiple users are using the traffic rpc, one user stopping the traffic results will stop the results for all users. This is an issue.

**Comment by hamidzr** [comment]
I get an error when I'm trying to open the traffic example even in master branch. 
`
if (body.resourceSets[0].estimatedTotal != 0) {
TypeError: Cannot read property 'estimatedTotal' of undefined
`

**Comment by brollb** [comment]
that's weird. I can check it out later today

**Comment by brollb** [comment]
Do you have the api key defined?

**Comment by brollb** [comment]
If that is the issue, we should fix it so the traffic example is disabled when the api key doesn't exist (like the movie db rpc)

**Comment by hamidzr** [comment]
yea please do email. That should probably be it. I assumed it would be hidden. I will then test and make it export only if there is an api key

**Comment by hamidzr** [comment]
This should be ready. do we need a foolproof testing or is this good enough?

**Comment by brollb** [comment]
Wanna just open a PR and I can check it out and let you know!
