### ISSUE TITLE
double selection in rpc call block

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#750]
When editing rpc input fields, selecting the first input field, then the second, then the first again, can result in the wrong field selected... This can also result in things like:

![image](https://cloud.githubusercontent.com/assets/4982789/22163085/0fc75e96-df17-11e6-9115-0199aef3d986.png)

**Comment by brollb** [comment]
@hamidzr can you check if this is still an issue? I think you may have fixed it when you improved the click handling of these fields

**Comment by hamidzr** [comment]
I can't find a problem with this anymore. Looks fixed
