### ISSUE TITLE
adding-google-trends-rpc

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#764]
Introducing a service to get google top trends for a map coordinate ( a country ) in English.

**Comment by hamidzr** [comment]
Problem with saving/exporting the project

**Comment by brollb** [comment]
?
Do you mean that you are having problems saving/exporting? If so, you can either make an issue or bring it up in the [gitter](https://gitter.im/NetsBlox/NetsBlox)

**Comment by hamidzr** [comment]
yes and apparently it is not limited to this branch. Maybe it is something wrong with my machine. I'll create a new issue
