### ISSUE TITLE
cant export/save project

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#779]
It happens even when exporting empty projects.
debug logs are attached.

[netsblox.zip](https://github.com/NetsBlox/NetsBlox/files/743721/netsblox.zip)

**Comment by brollb** [comment]
I am having a hard time replicating this. How exactly are you running into this?

Is the server throwing the exception on start (that's what it looks like in the logs)? The logs look like vantage (interactive repl when the server is running) is having a problem...

**Comment by hamidzr** [comment]
I start the server with npm start and I jump to saving / exporting the newly opened blank project. ( I collected these logs with DEBUG=netsblox:* npm start )

**Comment by hamidzr** [comment]
It works on a clean install of ubuntu, probably sth is incompatible with my setup.

**Comment by brollb** [comment]
Are you getting any logs in the client?

Have you tried removing `node_modules` and re-installing?
