### ISSUE TITLE
Enforce a naming convention for services

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#781]

**Comment by brollb** [comment]
The service names should be upper camelcase like `PublicRoles` and `GoogleMaps` (for staticmap)

**Comment by brollb** [comment]
Some renaming that we should do:
- staticmap -> GoogleMaps
- publicRoles -> PublicRoles
    - requestPublicRoleId -> getId
- kv-store -> KeyValueStore (we should also add a simplified version which just provides cloud variables)
- weather -> Weather or OpenWeatherMap?

**Comment by ellienguyen** [comment]
I think it depends on the name of the service we are asking data from. Most of the services the service name shows what it will return (BritishMuseum, MovieDB,...) but some might not (Thingspeak). So I think we should make sure the name should reflect both service name and what it will return

**Comment by hamidzr** [comment]
and I guess they should be in alphabetic order
