### ISSUE TITLE
adding waterWatch rpc and example

### ISSUE THREAD

**Issue by hamidzr** [NetsBlox/NetsBlox#796]
Making streamflow data accessible to students with an RPC and an example project.

**Comment by brollb** [comment]
Do you mean this api: https://waterdata.usgs.gov/nwis/rt ?

**Comment by hamidzr** [comment]
There is something seriously wrong with their website. Always super slow to load. I hope that they have done a better job with their api.

**Comment by hamidzr** [comment]
- create an rpc directory and file in procedures/
- create blocks file in lib/
- create an example project
- create a test

**Comment by hamidzr** [comment]
considering use of different message types for returning different related data. 
make the rpc more intuitive to use.
