### ISSUE TITLE
Teacher dashboard for use with classes

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#802]
We should provide a teacher dashboard for managing classrooms

**Comment by hamidzr** [comment]
let's write down the requirements, features and user interactions

**Comment by hamidzr** [comment]
Vue js looks like a good framework for the view layer.  It's very intuitive compared to react.

**Comment by hamidzr** [comment]
```
bin/netsblox-groups-rm-member.js
bin/netsblox-groups-rm.js
bin/netsblox-groups-add-member.js
bin/netsblox-groups.js
bin/netsblox-groups-list.js
bin/netsblox-groups-new.js
```
So the goal is to have an interface to provide these functionalities to teachers? 
+ sandboxing

**Comment by brollb** [comment]
That covers most of them but I think they will also need to be able to make users (and these users will be added automatically to the given group/class). Of course, since they should be able to add the users, they should probably be able to remove them as well (at least the ones in the given class).

In other words, CRUD operations on users (scoped to the given group) for now. In the future, we might want to add support for viewing student projects and stuff but it probably isn't to vital for a first cut.

**Comment by hamidzr** [comment]
I think we should have it as part of the front end. Maybe it would be better to start by working only on the dashboard but a have a look to the future that we want to integrate with the current landing page

**Comment by brollb** [comment]
This is now possible using https://github.com/netsblox/teacher-dashboard (deployed at https://dashboard.netsblox.org).
