### ISSUE TITLE
traffic doesn't show accidents when really zoomed in

### ISSUE THREAD

**Issue by brollb** [NetsBlox/NetsBlox#965]

**Comment by DarDoro** [comment]
There is a modified project
https://editor.netsblox.org/?action=present&Username=dardoro&ProjectName=Traffic

The original project has a flaw. 
![Me script pic](https://user-images.githubusercontent.com/16109071/82845171-c1897f80-9ee3-11ea-8ba4-8bf63fd942ff.png)
Ledft, Right, Up, Down, zoom buttons stops messages from traffic service but not retrigger it. This way it works as expected. 
![Me script pic (1)](https://user-images.githubusercontent.com/16109071/82845184-d239f580-9ee3-11ea-95b8-c9bdaa3ccd3c.png)
