### ISSUE TITLE
Cannot save the project - QuotaExceededError

### ISSUE THREAD

**Issue by ellienguyen** [NetsBlox/NetsBlox#975]
In some specific cases, the error is shown when saving the project
![image](https://cloud.githubusercontent.com/assets/18899970/26165532/e7ca0ed0-3af5-11e7-9335-5b58a9fdc595.png)
The error is not shown anymore if exporting the project and saving it in a different computer

[Geolocation.xml.zip](https://github.com/NetsBlox/NetsBlox/files/1008517/Geolocation.xml.zip)

**Comment by brollb** [comment]
It looks like this is related to the `localStorage` in your browser being full:

> the “QuotaExceededError: DOM Exception 22", which is triggered when the local storage limit for a certain host has been exceeded...

(https://medium.com/@nisalperi/how-i-solved-the-localstorage-quotaexceedederror-dom-exception-22-b69db46f0cee)

Can you run `Object.keys(localStorage).length` in your browser console?
