### ISSUE TITLE
New features for map

### ISSUE THREAD

**Issue by ellienguyen** [NetsBlox/NetsBlox#976]
I have added new sprites for pan up, down, left, right, zoom in, out and search. The attached file contains all the necessary xml files
[featuresForMap.zip](https://github.com/NetsBlox/NetsBlox/files/1008530/featuresForMap.zip)

**Comment by brollb** [comment]
This was added in a PR, right?

**Comment by ellienguyen** [comment]
Yes, I will close this issue
