### ISSUE TITLE
Mobile apps support with Cordova

### ISSUE THREAD

**Issue by volgy** [NetsBlox/NetsBlox#979]
Add necessary configuration, sources and patches for building Apache Cordova-based mobile appliacations of the user interface.
The mobile apps will not support code editing tasks but can open/join cloud and example projects and execute them.
The mobile app support will enable new sensor inputs. These might be developed under a separate issue.

**Comment by brollb** [comment]
This isn't the same as it deploys to windows, etc, but worth looking at http://snapp.citilab.eu/
