### ISSUE TITLE
Broken installation because fo lwip

### ISSUE THREAD

**Issue by TopNiz** [NetsBlox/NetsBlox#991]
`npm install ` works fine on mac os (Sierra). But, `lwip` is not installed because of `npm postinstall` issue.
I tried to install `lwip` separately and failed with `node-gyp rebuild`. It seems to be an actual issue with `lwip` which is blocking many dependant modules:
https://github.com/EyalAr/lwip/issues/278

I'm looking for an alternative...

**Comment by brollb** [comment]
Yeah, lwip can be finicky. As lwip is only used for generating thumbnails (it pads the image to make sure you get a good aspect ratio for things like facebook friendly links), it is not necessarily vital.

There are two ways to get around this:
 - make it fail more gracefully if lwip doesn't exist (no image padding and error message)
 - provide a docker image providing an lwip-friendly env

**Comment by brollb** [comment]
or, of course, replace lwip with a different image processing library
